# Request parameters
request_interval: 1
request_timeout: 10
max_retries: 3
contact_info: "" # Required for request headers

# Language model API configuration
language_model_base_url: "" # Required
language_model_name: "" # Required
language_model_api_key: "" # Required
# Add any extra parameters required by your language model API. e.g. {"enable_enhancement": True}
# If you don't have any extra parameters, you can leave this as an empty dictionary.
language_model_extra_params: {}

# Logging configuration
log_level: "info" # Options: "debug", "info", "warning", "error", "critical"
log_description_max_length: 15

# Cache configuration
# Required by Nominatim, which has a default cache expiration of 7 days.
cache_expiration_days: 7

# Update scheduling
update_interval_hours: 12 # set to 0 to disable automatic updates

# Frontend configuration
# Set to 0.0.0.0 to allow access from any IP address, or set to "localhost" to restrict access to the local machine.
http_server_host: "localhost"
http_server_port: 8080
base_url: "http://localhost:8080" # Used to generate sitemap URLs.

# IP blocklist configuration
# Interval in seconds to reload the IP blocklist from the file.
# DO NOT set this to 0 or a very low value, as it may cause performance issues.
reload_blocklist_interval_seconds: 1800

# HTTPS certificate configuration
# If you want to enable HTTPS, provide the paths to your certificate and key files.
# If you don't want to enable HTTPS, set both of these to null.
https_certificate_path: ""
https_key_path: ""
