# Request parameters
request_interval: 1
request_timeout: 10
max_retries: 3

# Language model API configuration
# Add any extra parameters required by your language model API. e.g. {"enable_enhancement": True}
# If you don't have any extra parameters, you can leave this as an empty dictionary.
language_model_extra_params: {}

# Logging configuration
log_level: "debug" # Options: "debug", "info", "warning", "error", "critical"
log_description_max_length: 15

# Cache configuration
# Required by Nominatim, which has a default cache expiration of 7 days.
cache_expiration_days: 7

# Update scheduling
update_interval_hours: 12 # set to 0 to disable automatic updates

# Frontend configuration
# Set to 0.0.0.0 to allow access from any IP address, or set to "localhost" to restrict access to the local machine.
http_server_host: "0.0.0.0"
http_server_port: 80
